name: Actions demo 1

on:
  push:
    branches: [main]
    paths-ignore: .github/**
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * 0"
  pull_request:
    branches: [main]
    
jobs:
  Build-demo:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "this job was triggered by: ${{github.event_name}}"
          echo "this is something"
      - uses: actions/checkout@v4.2.2

      - name: List all files
        run: |
  
    
