name: Actions demo 1

on:
  push:
    branches: [main]
    paths-ignore: .github/**
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * 0"
  pull_request:
    branches: [main]

  jobs:
    example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
  
    
